config/routes.rb
Phonebook::Application.routes.draw do
  get '/contacts', :to => "contacts#index", :as => 'contacts'
  get '/contacts/new', :to => 'contacts#new', :as => 'new_contact'
  post '/contacts/create', :to => 'contacts#create', :as => 'create_contact'
  get '/contacts/:id', :to => 'contacts#show', :as => 'contact'
  get '/contacts/:id/edit', :to => 'contacts#edit', :as => 'edit_contact'
  post '/contacts/:id/update', :to => 'contacts#update', :as => 'update_contact'
  delete '/contacts/:id', :to => 'contacts#destroy', :as => 'delete_contact'
  post '/', :to => 'contacts#search', :as => 'search_contact'
  
  root :to => 'contacts#index'

end

app/models/contact.rb
class Contact
  include Her::Model

  attributes :name, :numbers
  
  validates :name, presence: true
  validates :numbers, presence: true

  custom_post :search
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_filter :set_contact, :only => ["show", "edit", "update"]
  before_filter :sanitzie_numbers_params, :only => ["create", "update"]
  def index
    @contacts = Contact.all
  end
  
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    if @contact.valid? && @contact.save
      redirect_to contacts_path, :notice => "Contact created successfully."
    else
      @errors = @contact.errors.full_messages
    end
  end


  def show
  end

  def edit
  end

  def update
    @contact.assign_attributes(params[:contact])
    if @contact.valid? && Contact.save_existing(params[:id], params[:contact])
      redirect_to contacts_path, :notice => "Contact updated successfully."
    else
      @errors = @contact.errors.full_messages
    end
  end

  def destroy
    Contact.destroy_existing(params[:id])
    redirect_to contacts_path, :notice => "Contact deleted successfully."
  end

  def search
    @contacts = Contact.search(params[:contact][:search_attribute].to_sym => params[:contact][:search_query])
    render :index
  end

  private
  def set_contact
    @contact = Contact.find(params[:id])
  end

  def sanitzie_numbers_params
    params[:contact][:numbers] = params[:contact][:numbers].values
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
      base_title = "Phonebook"
    if page_title.empty?
      " #{base_title}"
    else 
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
  def form_submit_path
    params[:action] == "edit" || params[:action] == "update"  ? update_contact_path(@contact._id) : create_contact_path
  end
end

app/views/contacts/_form.html.erb
<% provide(:page_title, 'Contact Form') %>
<h1 style="text-align: center;">Contact Form</h1>
<%= form_tag(form_submit_path, :method => "post") do %>
  <% if @errors.present? %>
    <div id="error_explanation">
      <h2><%= pluralize(@errors.count, "error") %> prohibited this from being saved:</h2>

      <ul>
        <% @errors.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    
  <div class="field" style="width: 50%; margin-left: 25%;">
    <br />
    <div class="col-lg-12">
      <%= text_field_tag "contact[name]", @contact.name, :required => true, :class => 'form-control', :placeholder => "Name" %>
    <br />
    </div>
    <div class="number-container">
      <% if @contact.numbers.present? %>
        <% @contact.numbers.each_with_index do |number, index| %>
          <div class="col-lg-3">
            <%= select_tag "contact[numbers][#{index}][number_type]",  options_for_select([ "Work", "Personal", "Whatsapp" ], number["number_type"]), class: 'form-control' %>
          </div>
          <div class="col-lg-9">
            <%= number_field_tag "contact[numbers][#{index}][number]", number["number"], :required => true, :class => 'form-control', :placeholder => "Number" %>
            <br />
          </div>
        <% end %>
      <% else %>
        <div class="col-lg-3">
          <%= select_tag "contact[numbers][0][number_type]",  options_for_select([ "Work", "Personal", "Whatsapp" ]), class: 'form-control' %>
        </div>
        <div class="col-lg-9">
          <%= number_field_tag "contact[numbers][0][number]", '', :required => true, :class => 'form-control', :placeholder => "Number" %>
          <br />
        </div>
      <% end %>    
      <br />
    </div>
  </div>
  <div class="col-lg-12" style="width: 50%; margin-left: 25%;">
    <%= link_to "Add More", '#', :id => 'add_more_link' %>
    <br />
  </div>  
  <div class="actions col-lg-12" style="width: 50%; margin-left: 25%;">
    <%= submit_tag 'Submit', :class => "btn btn-success" %>
    <br />
  </div>
<% end %>
<div class="field col-lg-12" style="width: 50%; margin-left: 25%;">
  <% if ["edit", "update"].include?(params[:action]) %>
    <%= link_to 'Show', contact_path(@contact._id) %> |
  <% end %>
  <%= link_to 'Back', contacts_path %>
</div>  

<script type="text/javascript">
  $(document).ready(function(){
    number_field_count = <%= @contact.numbers.present? ? @contact.numbers.length : 1 %>;
    $('#add_more_link').click(function(){
      $('.number-container').append('<div class="col-lg-3"><select class="form-control" id="contact_'+ number_field_count +'_number_type" name="contact[numbers]['+ number_field_count +'][number_type]"><option value="Work">Work</option><option value="Personal">Personal</option>  <option value="Whatsapp">Whatsapp</option></select></div><div class="col-lg-9"><input class="form-control" id="contact_'+ number_field_count +'_number" name="contact[numbers]['+ number_field_count +'][number]" placeholder="Number" required="required" value="" type="number"><br></div>');
      number_field_count = number_field_count + 1;
      
    });
  });
</script>

app/views/contacts/create.html.erb
<%= render 'form' %>

app/views/contacts/edit.html.erb
<%= render 'form' %>

app/views/contacts/index.html.erb
<style type="text/css">
  table, th, td {
    padding: 2px;
  } 
</style>

<h3>Listing Contacts</h3>

<%= form_tag(search_contact_path, :method => 'post') do %>
  <div class="col-lg-12">
    <div class="col-lg-3">
      <select name="contact[search_attribute]">
        <option value="name">Name</option>
        <option value="phone_number_1">Phone Number 1</option>
      </select>
    </div>
      
    <div class="col-lg-7">
      <%= text_field_tag "contact[search_query]", '', :placeholder => "Name/Phone Numer", :class => 'form-control' %>
    </div>
  </div>
  <br />
  <br />
  <br />
<% end %>  

<table class="table table-bordered table-stripped">
  <tr>
    <th>Name</th>
    <th>Number</th>
    <th colspan="3">Actions</th>
  </tr>

  <% @contacts.each do |contact| %>
    <tr>
      <td><%= contact.name %></td>
      <td><%= contact.numbers[0]["number"] %></td>
      <td><%= link_to 'Edit', edit_contact_path(contact._id) %></td>
      <td><%= link_to 'View',  contact_path(contact._id) %></td>
      <td><%= link_to 'Delete', delete_contact_path(contact._id), :data => { :confirm => "Are you sure?" }, :method => :delete %></td>
      
    </tr>
  <% end -%>  
</table>
<p><%= link_to 'New Contact',  new_contact_path %></p>

app/views/contacts/new.html.erb
<%= render 'form' %>

app/views/contacts/show.html.erb
<% provide(:page_title, 'Show Contact') %>
<h3>Showing Contact</h3>
<p>Name: <%= @contact.name.humanize %></p>
<% @contact.numbers.each do |number| %>
    <p><%= "#{number["number_type"].humanize} Number" %>: <%= number["number"] %></p>
<% end %>
<p><%= link_to 'Edit', edit_contact_path(@contact._id) %> | <%= link_to 'Delete', delete_contact_path(@contact._id), :data => { :confirm => "Are you sure?" }, :method => :delete %> | <%= link_to 'Back', contacts_path %></p>

app/views/contacts/update.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= raw(full_title(yield(:page_title))) %> </title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag "http://getbootstrap.com/dist/css/bootstrap.min.css" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "http://getbootstrap.com/dist/js/bootstrap.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<br />
<% if notice %>
  <div class="alert alert-warning alert-dismissible fade in" role="alert"> 
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">×</span>
    </button>
    <strong><%= notice %></strong>
  </div>
  <p style="color: #8A6D3B;"></p>
<% end %>
<%= yield %>
</div>
</body>
</html>